name: My custom template2
description: This is a test custom template
title: "[Bug]: "
labels: ["need this label"]
projects: ["Test the Best project"]
assignees:
body:
  - type: markdown
    attributes:
      value: |
        ## Fill in some stuff here
  - type: textarea
    id: stuff
    attributes:
      label: Stuff?
      description: Stuff to fill in?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Fill in more stuff here
  - type: textarea
    id: more-stuff
    attributes:
      label: More Stuff?
      description: More Stuff to fill in?
      value: "More stuff"
    validations:
      required: true


